config/routes.rb
Review3App::Application.routes.draw do

  # Routes for the Author resource:
  # CREATE
  get '/authors/new', controller: 'authors', action: 'new', as: 'new_author'
  post '/authors', controller: 'authors', action: 'create'

  # READ
  get '/authors', controller: 'authors', action: 'index', as: 'authors'
  get '/authors/:id', controller: 'authors', action: 'show', as: 'author'

  # UPDATE
  get '/authors/:id/edit', controller: 'authors', action: 'edit', as: 'edit_author'
  put '/authors/:id', controller: 'authors', action: 'update'

  # DELETE
  delete '/authors/:id', controller: 'authors', action: 'destroy'
  #------------------------------

  # Routes for the Book resource:
  # CREATE
  get '/books/new', controller: 'books', action: 'new', as: 'new_book'
  post '/books', controller: 'books', action: 'create'

  # READ
  get '/books', controller: 'books', action: 'index', as: 'books'
  get '/books/:id', controller: 'books', action: 'show', as: 'book'

  # UPDATE
  get '/books/:id/edit', controller: 'books', action: 'edit', as: 'edit_book'
  put '/books/:id', controller: 'books', action: 'update'

  # DELETE
  delete '/books/:id', controller: 'books', action: 'destroy'
  #------------------------------

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find_by_id(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new
    @author.name = params[:name]
    
    if @author.save
            redirect_to authors_url
          else
      render 'new'
    end
  end

  def edit
    @author = Author.find_by_id(params[:id])
  end

  def update
    @author = Author.find_by_id(params[:id])
    @author.name = params[:name]
    
    if @author.save
            redirect_to authors_url
          else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find_by_id(params[:id])
    @author.destroy
        redirect_to authors_url
      end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find_by_id(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new
    @book.title = params[:title]
    @book.author_id = params[:author_id]

    if @book.save
            redirect_to books_url
          else
      render 'new'
    end
  end

  def edit
    @book = Book.find_by_id(params[:id])
  end

  def update
    @book = Book.find_by_id(params[:id])
    @book.title = params[:title]
    @book.author_id = params[:author_id]

    if @book.save
            redirect_to books_url
          else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find_by_id(params[:id])
    @book.destroy
        redirect_to books_url
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/edit.html.erb
<h1>Editing Author #<%= @author.id %></h1>


<%= form_tag(author_url(@author), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @author.name %>
  </div>

  
  <div>
    <%= submit_tag "Update Author" %>
  </div>

<% end %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<p><%= link_to 'Add a New Author', new_author_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.name %></td>
  
      <td><%= link_to 'Show', author_url(author) %></td>
      <td><%= link_to 'Edit', edit_author_url(author) %></td>
      <td><%= link_to 'Destroy', author_url(author), method: 'delete', data: { confirm: "Do you really want to delete this author?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<h1>New Author</h1>


<%= form_tag(authors_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  
  <div>
    <%= submit_tag "Create Author" %>
  </div>
<% end %>

app/views/authors/show.html.erb
<h1>Author #<%= @author.id %></h1>

<p>
  <b>Name:</b>
  <%= @author.name %>
</p>

<p>
  <b>Books:</b>
  <ul>
    <% @author.books.each do |book| %>
      <li><%= book.title %></li>
    <% end %>
  </ul>
</p>

app/views/books/edit.html.erb
<h1>Editing Book #<%= @book.id %></h1>


<%= form_tag(book_url(@book), method: 'put') do %>

  <div>
    <%= label_tag :title %><br />
    <%= text_field_tag :title, @book.title %>
  </div>

  <div>
    <%= label_tag :author_id %><br />
    <%= number_field_tag :author_id, @book.author_id %>
  </div>

  <div>
    <%= submit_tag "Update Book" %>
  </div>

<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<p><%= link_to 'Add a New Book', new_book_url %></p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
  
      <td><%= link_to 'Show', book_url(book) %></td>
      <td><%= link_to 'Edit', edit_book_url(book) %></td>
      <td><%= link_to 'Destroy', book_url(book), method: 'delete', data: { confirm: "Do you really want to delete this book?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>


<%= form_tag(books_url, method: 'post') do %>


  <div>
    <%= label_tag :title %><br />
    <%= text_field_tag :title %>
  </div>

  <div>
    <%= label_tag :author_id %><br />
    <%= number_field_tag :author_id %>
  </div>


  <div>
    <%= submit_tag "Create Book" %>
  </div>
<% end %>

app/views/books/show.html.erb
<h1>Book #<%= @book.id %></h1>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author.name %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Review3App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>